<?php
return [
    'dashboard'         => 'modules/dashboard.php',
    'clientsignup'      => 'modules/client/clientsignup.php',
    'clientlogin'       => 'modules/clientlogin.php',
    'home'              => 'modules/client/home.php',
    'agentlogin'        => 'modules/agentlogin.php',
    'agentDashboard'    => 'modules/agent/agentDashboard.php',
    'adminlogin'        => 'modules/adminlogin.php',
    'adminDashboard'    => 'modules/admin/adminDashboard.php',
    'add-property'      => 'modules/admin/add-property.php',
    'edit-property'      => 'modules/admin/edit-property.php',
    'exploreproperty'   => 'modules/admin/exploreproperty.php',
    'print-properties'  => '../reports/print-properties.php',
    'print-agents'  => '../reports/print-agents.php',
    'agentregister'   => 'modules/admin/agentregister.php',
    'edit-agent'   => 'modules/admin/edit-agent.php',
    'agentprofile'   => 'modules/admin/agentprofile.php',
    'agentdisplay'   => 'modules/admin/agentdisplay.php',
    'property-detail'   => 'modules/admin/property-detail.php',
    'userprofile'   => 'modules/userprofile.php',
    'agentuserProfile'   => 'modules/agent/agentuserProfile.php',
    'clientPreQual'   => 'modules/agent/clientPreQual.php',
    'logout'            => 'modules/logout.php',
    'calendar'          => 'modules/calendar.php',
    'pre-qual'          => 'modules/pre-qual.php'
];
