<?php
return [
    'Admin' => [
        'adminDashboard',
        'add-property',
        'edit-property',
        'exploreproperty',
        'print-properties',
        'print-agents',
        'agentregister',
        'edit-agent',
        'agentprofile',
        'agentdisplay',
        'property-detail',
        'clientReservation',
        'clientReservationDetails',
        'logout',
    ],
    'Agent' => [
        'agentlogin',
        'agentuserProfile',
        'agentDashboard',
        'userprofile',
        'clientPreQual',
        'clientPreDetails',
        'exploreproperty',
        'print-properties',
        'logout'
    ],
    'Client' => [
        'clientsignup',
        'home',
        'clientInfoSheet',
        'spouseInfoSheet',
        'reservations',
        'reservation-view',
        'edit-clientprofile',
        'clientprofile',
        'logout',
        'clientlogin',
        'dashboard',
        'calendar',
        'pre-qual',
        'clientInfoSheet-view'
    ],
];
